version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-friendship-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq-service
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password